//
//  AutoIntentionService.swift
//  Attunetion
//
//  Created by Nathan Fennel on 12/2/25.
//

import Foundation
import SwiftData

/// Service for managing AI-generated intentions
@MainActor
class AutoIntentionService {
    private let apiClient: APIClient
    private let intentionRepository: IntentionRepository
    private let userProfileRepository: UserProfileRepository
    private let modelContext: ModelContext
    
    init(
        apiClient: APIClient,
        intentionRepository: IntentionRepository,
        userProfileRepository: UserProfileRepository,
        modelContext: ModelContext
    ) {
        self.apiClient = apiClient
        self.intentionRepository = intentionRepository
        self.userProfileRepository = userProfileRepository
        self.modelContext = modelContext
    }
    
    /// Generate and save intentions for the current week
    func generateCurrentWeekIntentions() async throws {
        let profile = userProfileRepository.getOrCreateProfile()
        
        guard profile.autoGenerateEnabled else {
            throw AutoIntentionError.autoGenerateDisabled
        }
        
        guard !profile.userInfo.isEmpty else {
            throw AutoIntentionError.noUserInfo
        }
        
        // Calculate current week start (Monday)
        let calendar = Calendar.current
        let today = Date()
        let weekday = calendar.component(.weekday, from: today)
        let daysFromMonday = (weekday + 5) % 7 // Convert Sunday=1 to Monday=0
        let weekStart = calendar.date(byAdding: .day, value: -daysFromMonday, to: today)!
        let weekStartStartOfDay = calendar.startOfDay(for: weekStart)
        
        // Check if we already generated for this week
        if let lastGenerated = profile.lastGeneratedWeekStart {
            let lastGeneratedStartOfDay = calendar.startOfDay(for: lastGenerated)
            if calendar.isDate(lastGeneratedStartOfDay, equalTo: weekStartStartOfDay, toGranularity: .weekOfYear) {
                throw AutoIntentionError.alreadyGeneratedForWeek
            }
        }
        
        // Get previous intentions for context (last 10 intentions)
        let allIntentions = intentionRepository.getAll()
        let previousIntentions = Array(allIntentions.prefix(10)).map { intention in
            PreviousIntentionForGeneration(
                text: intention.text,
                scope: intention.scope.rawValue,
                date: ISO8601DateFormatter().string(from: intention.date)
            )
        }
        
        // Call API to generate intentions
        let response = try await apiClient.generateWeeklyIntentions(
            userInfo: profile.userInfo,
            weekStartDate: weekStartStartOfDay,
            previousIntentions: previousIntentions
        )
        
        // Parse dates and create Intention objects
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        dateFormatter.locale = Locale(identifier: "en_US_POSIX")
        
        for weeklyIntention in response.intentions {
            guard let date = dateFormatter.date(from: weeklyIntention.date) else {
                print("Warning: Failed to parse date: \(weeklyIntention.date)")
                continue
            }
            
            guard let scope = IntentionScope(rawValue: weeklyIntention.scope) else {
                print("Warning: Invalid scope: \(weeklyIntention.scope)")
                continue
            }
            
            // Check if intention already exists for this date/scope
            if intentionRepository.getIntention(for: date, scope: scope) != nil {
                continue // Skip if already exists
            }
            
            let intention = Intention(
                text: weeklyIntention.text,
                scope: scope,
                date: date,
                aiGenerated: true
            )
            
            try intentionRepository.create(intention)
        }
        
        // Update profile with last generated week and increment generation count
        profile.lastGeneratedWeekStart = weekStartStartOfDay
        profile.totalGenerations += 1
        try userProfileRepository.update(profile)
    }
    
    /// Check if intentions need to be generated for the current week
    func shouldGenerateIntentions() -> Bool {
        let profile = userProfileRepository.getOrCreateProfile()
        
        guard profile.autoGenerateEnabled else {
            return false
        }
        
        guard !profile.userInfo.isEmpty else {
            return false
        }
        
        // Calculate current week start
        let calendar = Calendar.current
        let today = Date()
        let weekday = calendar.component(.weekday, from: today)
        let daysFromMonday = (weekday + 5) % 7
        let weekStart = calendar.date(byAdding: .day, value: -daysFromMonday, to: today)!
        let weekStartStartOfDay = calendar.startOfDay(for: weekStart)
        
        // Check if we already generated for this week
        if let lastGenerated = profile.lastGeneratedWeekStart {
            let lastGeneratedStartOfDay = calendar.startOfDay(for: lastGenerated)
            if calendar.isDate(lastGeneratedStartOfDay, equalTo: weekStartStartOfDay, toGranularity: .weekOfYear) {
                return false
            }
        }
        
        return true
    }
}

enum AutoIntentionError: LocalizedError {
    case autoGenerateDisabled
    case noUserInfo
    case alreadyGeneratedForWeek
    case apiError(Error)
    
    var errorDescription: String? {
        switch self {
        case .autoGenerateDisabled:
            return "Auto-generation is disabled. Enable it in your profile settings."
        case .noUserInfo:
            return "Please add information about yourself in your profile to generate personalized intentions."
        case .alreadyGeneratedForWeek:
            return "Intentions have already been generated for this week."
        case .apiError(let error):
            return "Failed to generate intentions: \(error.localizedDescription)"
        }
    }
}

